const CLAIM_STATUS = {
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  MORE_INFO: 'MORE_INFO',
  ACTION_NEEDED: 'ACTION_NEEDED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  WITHDRAWN: 'WITHDRAWN',
  COMPLETED: 'COMPLETED',
};

const WORKFLOW_ORDER = ['STUDENT', 'HOD', 'ACCOUNTS'];

module.exports = {
  CLAIM_STATUS,
  WORKFLOW_ORDER,
};

